config/routes.rb
Rails.application.routes.draw do
  delete 'favourites/del', to: 'favourites#del'
  resources :favourites

  get 'users/profile'
  resources :reviews
  resources :authors
  resources :categories
  resources :mangas
  devise_for :users
  get 'home/about'
  root 'home#index'
end

app/models/manga.rb
class Manga < ApplicationRecord
    belongs_to :author
    has_many :reviews
	has_many :favourites
    belongs_to :category
    # has_and_belongs_to_many :users, join_table: 'favourites'
    
    has_one_attached :image

    def get_author
		if self.author
			self.author.name
		else
			"Deleted"
		end
    end
    
    def get_category
		if self.category
			self.category.category
		else
			"Deleted"
		end
    end

end

app/controllers/mangas_controller.rb
class MangasController < ApplicationController
  before_action :set_manga, only: %i[ show edit update destroy ]

  # GET /mangas or /mangas.json
  def index
    @mangas = Manga.all
  end

  # GET /mangas/1 or /mangas/1.json
  def show
    @review = Review.new

    @favourites = Favourite.new
    @is_active = false;
    if user_signed_in?
        @is_active = Favourite.exists?(user_id: current_user.id, manga_id: params[:id]) 
    end
  end

  # GET /mangas/new
  def new
    @manga = Manga.new
  end

  # GET /mangas/1/edit
  def edit
  end

  # POST /mangas or /mangas.json
  def create
    @manga = Manga.new(manga_params)

    respond_to do |format|
      if @manga.save
        format.html { redirect_to @manga, notice: "Manga was successfully created." }
        format.json { render :show, status: :created, location: @manga }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @manga.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mangas/1 or /mangas/1.json
  def update
    respond_to do |format|
      if @manga.update(manga_params)
        format.html { redirect_to @manga, notice: "Manga was successfully updated." }
        format.json { render :show, status: :ok, location: @manga }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @manga.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mangas/1 or /mangas/1.json
  def destroy
    @manga.destroy
    respond_to do |format|
      format.html { redirect_to mangas_url, notice: "Manga was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manga
      @manga = Manga.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def manga_params
      params.require(:manga).permit(:title, :category_id, :author_id, :description, :image)
    end
end

app/helpers/mangas_helper.rb
module MangasHelper
end

app/views/mangas/_form.html.erb
<%= form_with(model: manga, local: true) do |form| %>
  <% if manga.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(manga.errors.count, "error") %> prohibited this manga from being saved:</h2>

      <ul>
        <% manga.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field col-sm-5">
    <%= form.label :title, class:"col-form-label fs-4" %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="field col-sm-5">
    <%= form.label :category_id, class:"col-form-label fs-4" %>
    <%= form.collection_select :category_id, Category.all, :id, :category, class:"form-control"  %>
  </div>

  <div class="field col-sm-5">
    <%= form.label :author_id, class:"col-form-label fs-4" %>
    <%= form.collection_select :author_id, Author.all, :id, :name, class:"form-control" %>
  </div>

  <div class="field col-sm-5">
    <%= form.label :description, class:"col-form-label fs-4"  %>
    <%= form.text_area :description, class:"form-control"  %>
  </div>
  
  <div class="field col-sm-5">
    <%= form.label :image, class:"col-form-label fs-4" %>
    <%= form.file_field :image, class:"form-control" %><br>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mangas/edit.html.erb
<h1>Editing Manga</h1>

<%= render 'form', manga: @manga %>

<%= link_to 'Back', mangas_path, class:"btn btn-outline-success" %>

app/views/mangas/index.html.erb
<h1>Manga</h1>

<% if @mangas.count > 0 %>
<table class="table">
  <thead class="table-dark fs-5">
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th>Author</th>
      <th>Description</th>
    </tr>
  </thead>

  <tbody>
    <% @mangas.each_with_index do |manga| %>
      <tr>
        <td><%= link_to manga.title, manga, class: "btn btn-outline-primary text-break" %> </td>
        <td><%= link_to manga.get_category, manga.category, class: "btn btn-outline-dark" %> </td>
        <td><%= link_to manga.get_author, manga.author, class: "btn btn-outline-dark " %> </td>
        <% if manga.description != "" %>
          <td><%= link_to manga.description, "#", class: "btn btn-outline-dark text-break text-start" %> </td>
        <% else %>
          <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% else %>
  <p class="fs-4">No manga</p>
<% end %>

<br>

<%= link_to 'New Manga', new_manga_path, class: "btn btn-outline-success" %>

app/views/mangas/new.html.erb
<h1>New Manga</h1>

<%= render 'form', manga: @manga %>

<%= link_to 'Back', mangas_path, class:"btn btn-outline-success" %>

app/views/mangas/show.html.erb
<p>
  <% if @manga.image.attached? %>
    <%= image_tag @manga.image %>
  <% end %>
</p>

<p class="fs-3">
<strong>Title:</strong>
<%= link_to @manga.title, "#", class:"btn btn-outline-dark" %>
</p>

<p class="fs-3">
<strong>Category:</strong>
<%= link_to @manga.get_category, @manga.category, class:"btn btn-outline-dark" %>
</p>

<p class="fs-3">
<strong>Author:</strong>
<%= link_to @manga.get_author, @manga.author, class:"btn btn-outline-dark" %>
</p>

<p class="fs-3">
<strong>Description:</strong>
<% if @manga.description != "" %>
  <%= link_to @manga.description, "#", class:"btn btn-outline-dark" %>
<% end %>  
</p>

<p class="fs-3">
<strong>Rate:</strong>
<%= link_to number_with_precision(@manga.rate, :precision => 2), "#", class:"btn btn-outline-dark" %>
</p>


<div class="btn-group" role="group">
    <%= link_to 'Back', mangas_path, class:"btn btn-outline-dark" %>
  <%= link_to 'Edit', edit_manga_path(@manga), class:"btn btn-outline-primary" %>     
  <td><%= link_to 'Delete', @manga, method: :delete, data: { confirm: 'Are you sure?'},  class: "btn btn-outline-danger" %></td>
  
  <% if !@is_active %>
    <%= form_with(model: @favourites, local: true) do |form| %>
    <%= form.hidden_field :user_id, :value => current_user.id %>
    <%= form.hidden_field :manga_id, :value => @manga.id %>
    <button type="submit" class="btn btn-outline-info">Add Favouries</button>
    <% end %>
  <% else %> 
    <%# <button type="button" class="btn btn-info">Add Favouries</button>  %>
    <a class="btn btn-info" data-method="delete" href="/favourites/del?user_id=<%= current_user.id%>&manga_id=<%= @manga.id %>">Remove favourite</a>
  <% end %> 
  
</div>

<br><br><br>
<p class="fs-3">Review Form</p>
 <%= form_with(model: @review, local: true) do |form| %>
    <div class="form-group">
     <label for="customRange1">Rate: </label>
     <%= form.range_field :rate, id:"rate", in:1..10 %>
     <span id="demo"></span>/10
   </div>
   <div class= "field col-sm-5">
     <%= form.text_area :comment, class:"form-control" %>
     <%= form.hidden_field :user_id, :value => current_user.id %>
     <%= form.hidden_field :manga_id, :value => @manga.id %>
   </div>
   <div class="actions">
     <%= form.submit %>
   </div>
 <% end %>

<br><br><br>
<% if @manga.reviews.count > 0 %>
<p class="fs-3">Review List</p>
<table class="table fs-6">
  <thead class="table-dark">
    <tr>
      <th>#</th>
      <th>User</th>
      <th>Rate</th>
      <th>Review</th>
      <th>Time</th>
    </tr>
  </thead>

  <tbody>
    <% @manga.reviews.each_with_index do |review, i| %>
      <tr>
        <td><%= link_to i+1, "#", class:"btn btn-outline-primary" %></td>
        <% if review.user.name != "" %>
	  <td><%= link_to review.user.name, "#", class: "btn btn-outline-dark" %> </td>
        <% else %>
	  <td><%= link_to review.user.email, "#", class: "btn btn-outline-dark" %> </td>
        <% end %>    
        <td><%= link_to review.rate, "#", class:"btn btn-outline-dark" %></td>
        <td><%= link_to review.comment, "#", class:"btn btn-outline-dark" %></td>
        <td><%= link_to review.created_at.localtime.strftime("%d/%m/%Y %H:%M:%S"), "#", class:"btn btn-outline-dark" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p class="fs-4">No review</p>
<% end %>
<script>
var slider = document.getElementById("rate");
var output = document.getElementById("demo");
output.innerHTML = slider.value;

slider.oninput = function() {
  output.innerHTML = this.value ;
}
</script>