config/routes.rb
Rails.application.routes.draw do
  delete 'favourites/del', to: 'favourites#del'
  resources :favourites

  get 'users/profile'
  resources :reviews
  resources :authors
  resources :categories
  resources :mangas
  devise_for :users
  get 'home/about'
  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Wibu World', root_path, class:"navbar-brand fs-3"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item fs-5">
          <%= link_to 'About Us', home_about_path, class:"nav-link" %>
        </li>

        <% if user_signed_in? %>
            <li class="nav-item fs-5">
              <%= link_to 'Manga', mangas_path, class:"nav-link" %>
            </li>
            <li class="nav-item fs-5">
              <%= link_to 'Author', authors_path, class:"nav-link" %>
            </li>
            <li class="nav-item fs-5">
              <%= link_to 'Category', categories_path, class:"nav-link" %>
            </li>
            <li class="nav-item fs-5">
              <%= link_to 'Recent Reviews', reviews_path, class:"nav-link" %>
            </li>
            <li class="nav-item btn-group">
              <button type="button" class="btn btn-outline-secondary dropdown-toggle fs-5" data-bs-toggle="dropdown" aria-expanded="false"> 
                <% if current_user.name != "" %>
                  <%= current_user.name %>
                <% else %>
                  <%= current_user.email %>
                <% end %>
              </button>
              <ul class="dropdown-menu dropdown-menu-dark fs-5" aria-labelledby="dropdownMenuClickableInside">
                <li><%= link_to 'My Profile', users_profile_path, class:"dropdown-item" %></li>
                <li><%= link_to 'Edit Profile', edit_user_registration_path, class:"dropdown-item" %></li>
                <li><%= link_to 'My Favourites', favourites_path, class:"dropdown-item" %></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete, class:"dropdown-item" %></li>
              </ul>
            </li>
        <% else %>
            <li class="nav-item fs-5">
              <%= link_to 'Log in', new_user_session_path, class:"nav-link" %>
            </li>
            <li class="nav-item fs-5">
              <%= link_to 'Sign up', new_user_registration_path, class:"nav-link" %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<div class="container-fluid p-5 bg-primary text-white text-center">
  <h1>Team wibu</h1>
  <h2>Review manga</h2> 
</div>
<div class="mx-auto" style="width: 300px;">

<h2 text-align: center> Team Member </h2>
</div>

<div class="container mt-5">
    <div class="row">
    <div class="col-sm-4">
        <h3>Đoàn Xuân Hưng</h3>
        <p>20184117</p>
    </div>
    <div class="col-sm-4">
        <h3>Nguyễn Trung Đức</h3>
        <p> 20184073</p>
    </div>
    <div class="col-sm-4">
        <h3>Trần Đức Quân</h3>        
        <p>20184178</p>
    </div>
    <div class="col-sm-4">
        <h3>Lê Ngọc Long</h3>        
        <p>20184137</p>
    </div>
    <div class="col-sm-4">
        <h3>Đặng Duy Cương </h3>        
        <p>20180033</p>
    </div>
</div>

app/views/home/index.html.erb
<div class="container-fluid p-5 bg-primary text-white text-center">
  <h1>Team wibu</h1>
  <h2>Review manga</h2> 
</div>
  